-- ASF's initial, forward-only PostgreSQL schema.
--
-- UUIDs are generated by the Rust control plane (UUIDv7), so this migration
-- intentionally does not require a PostgreSQL extension.
-- SHA-256 references use the same representation as `crypto::sha256_digest`:
-- the literal `sha256:` prefix followed by 64 lowercase hexadecimal digits.

CREATE FUNCTION asf_valid_budget_limits(candidate jsonb) RETURNS boolean
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT CASE
        WHEN jsonb_typeof(candidate) <> 'object' THEN false
        WHEN candidate ?& ARRAY[
                'max_cost_microunits',
                'max_input_tokens',
                'max_output_tokens',
                'max_implementer_invocations',
                'max_reviewer_invocations',
                'max_fix_iterations',
                'max_wall_time_seconds',
                'max_external_api_calls'
             ]
         AND candidate - ARRAY[
                'max_cost_microunits',
                'max_input_tokens',
                'max_output_tokens',
                'max_implementer_invocations',
                'max_reviewer_invocations',
                'max_fix_iterations',
                'max_wall_time_seconds',
                'max_external_api_calls'
             ] = '{}'::jsonb
         AND jsonb_typeof(candidate -> 'max_cost_microunits') = 'number'
         AND jsonb_typeof(candidate -> 'max_input_tokens') = 'number'
         AND jsonb_typeof(candidate -> 'max_output_tokens') = 'number'
         AND jsonb_typeof(candidate -> 'max_implementer_invocations') = 'number'
         AND jsonb_typeof(candidate -> 'max_reviewer_invocations') = 'number'
         AND jsonb_typeof(candidate -> 'max_fix_iterations') = 'number'
         AND jsonb_typeof(candidate -> 'max_wall_time_seconds') = 'number'
         AND jsonb_typeof(candidate -> 'max_external_api_calls') = 'number'
         AND (candidate ->> 'max_cost_microunits') ~ '^[0-9]+$'
         AND (candidate ->> 'max_input_tokens') ~ '^[0-9]+$'
         AND (candidate ->> 'max_output_tokens') ~ '^[0-9]+$'
         AND (candidate ->> 'max_implementer_invocations') ~ '^[1-9][0-9]*$'
         AND (candidate ->> 'max_reviewer_invocations') ~ '^[1-9][0-9]*$'
         AND (candidate ->> 'max_fix_iterations') ~ '^[0-9]+$'
         AND (candidate ->> 'max_wall_time_seconds') ~ '^[1-9][0-9]*$'
         AND (candidate ->> 'max_external_api_calls') ~ '^[0-9]+$'
        THEN
            (candidate ->> 'max_cost_microunits')::numeric <= 18446744073709551615
            AND (candidate ->> 'max_input_tokens')::numeric <= 18446744073709551615
            AND (candidate ->> 'max_output_tokens')::numeric <= 18446744073709551615
            AND (candidate ->> 'max_implementer_invocations')::numeric <= 4294967295
            AND (candidate ->> 'max_reviewer_invocations')::numeric <= 4294967295
            AND (candidate ->> 'max_fix_iterations')::numeric <= 4294967295
            AND (candidate ->> 'max_wall_time_seconds')::numeric <= 18446744073709551615
            AND (candidate ->> 'max_external_api_calls')::numeric <= 4294967295
        ELSE false
    END;
$$;

CREATE FUNCTION asf_valid_identity_requirements(candidate jsonb) RETURNS boolean
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT CASE
        WHEN jsonb_typeof(candidate) <> 'object' THEN false
        ELSE
            candidate ?& ARRAY['implementer', 'local_reviewer', 'pr_reviewer']
            AND candidate - ARRAY['implementer', 'local_reviewer', 'pr_reviewer'] = '{}'::jsonb
            AND jsonb_typeof(candidate -> 'implementer') = 'string'
            AND jsonb_typeof(candidate -> 'local_reviewer') = 'string'
            AND jsonb_typeof(candidate -> 'pr_reviewer') = 'string'
            AND (candidate ->> 'implementer')
                ~ '^(claude|codex):[A-Za-z0-9][A-Za-z0-9_-]{0,63}$'
            AND (candidate ->> 'local_reviewer')
                ~ '^(claude|codex):[A-Za-z0-9][A-Za-z0-9_-]{0,63}$'
            AND (candidate ->> 'pr_reviewer')
                ~ '^(claude|codex):[A-Za-z0-9][A-Za-z0-9_-]{0,63}$'
            AND (candidate ->> 'implementer') <> (candidate ->> 'local_reviewer')
            AND (candidate ->> 'implementer') <> (candidate ->> 'pr_reviewer')
    END;
$$;

CREATE TABLE tenants (
    id uuid PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    display_name text NOT NULL,
    status text NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'MAINTENANCE', 'DISABLED')),
    aggregate_version bigint NOT NULL DEFAULT 1 CHECK (aggregate_version > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (btrim(slug) <> ''),
    CHECK (btrim(display_name) <> '')
);

CREATE TABLE repositories (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    forge text NOT NULL DEFAULT 'github' CHECK (forge = 'github'),
    owner text NOT NULL,
    name text NOT NULL,
    repository_url text NOT NULL,
    default_branch text NOT NULL,
    active boolean NOT NULL DEFAULT true,
    wip_limit integer NOT NULL DEFAULT 1 CHECK (wip_limit > 0),
    required_checks jsonb NOT NULL DEFAULT '[]'::jsonb
        CHECK (jsonb_typeof(required_checks) = 'array'),
    risk_rules jsonb NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(risk_rules) = 'object'),
    identity_requirements jsonb NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(identity_requirements) = 'object'),
    default_policy_digest text,
    autonomy_level text NOT NULL DEFAULT 'OBSERVE'
        CHECK (autonomy_level IN (
            'OBSERVE',
            'SUPERVISED_PR',
            'AUTOMATIC_VERIFIED_PR',
            'GUARDED_MERGE_CANDIDATE',
            'GUARDED_MERGE_ENABLED'
        )),
    aggregate_version bigint NOT NULL DEFAULT 1 CHECK (aggregate_version > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, forge, owner, name),
    CHECK (btrim(owner) <> ''),
    CHECK (btrim(name) <> ''),
    CHECK (btrim(repository_url) <> ''),
    CHECK (btrim(default_branch) <> ''),
    CHECK (
        default_policy_digest IS NULL
        OR default_policy_digest ~ '^sha256:[0-9a-f]{64}$'
    )
);

CREATE TABLE policy_versions (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    repository_id uuid,
    scope text NOT NULL CHECK (scope IN ('TENANT', 'REPOSITORY', 'WORK_CLASS')),
    schema_version text NOT NULL,
    digest text NOT NULL CHECK (digest ~ '^sha256:[0-9a-f]{64}$'),
    canonical_bytes bytea NOT NULL CHECK (octet_length(canonical_bytes) > 0),
    policy jsonb NOT NULL CHECK (jsonb_typeof(policy) = 'object'),
    created_by text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    expires_at timestamptz,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, digest),
    FOREIGN KEY (tenant_id, repository_id)
        REFERENCES repositories(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(schema_version) <> ''),
    CHECK (btrim(created_by) <> ''),
    CHECK (expires_at IS NULL OR expires_at > created_at),
    CHECK (
        (scope = 'REPOSITORY' AND repository_id IS NOT NULL)
        OR (scope <> 'REPOSITORY')
    )
);

ALTER TABLE repositories
    ADD CONSTRAINT repositories_default_policy_fk
    FOREIGN KEY (tenant_id, default_policy_digest)
    REFERENCES policy_versions(tenant_id, digest)
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE source_snapshots (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    repository_id uuid,
    source_system text NOT NULL CHECK (source_system IN ('LINEAR', 'API', 'GITHUB')),
    external_id text NOT NULL,
    source_revision text NOT NULL,
    source_url text,
    normalized_content jsonb NOT NULL CHECK (jsonb_typeof(normalized_content) = 'object'),
    content_digest text NOT NULL CHECK (content_digest ~ '^sha256:[0-9a-f]{64}$'),
    connector_identity text NOT NULL,
    captured_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    source_updated_at timestamptz NOT NULL,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, source_system, external_id, source_revision, content_digest),
    FOREIGN KEY (tenant_id, repository_id)
        REFERENCES repositories(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(external_id) <> ''),
    CHECK (btrim(source_revision) <> ''),
    CHECK (btrim(connector_identity) <> '')
);

CREATE INDEX source_snapshots_external_lookup_idx
    ON source_snapshots (tenant_id, source_system, external_id, captured_at DESC);

CREATE TABLE work_items (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    source_snapshot_id uuid NOT NULL,
    source_system text NOT NULL CHECK (source_system IN ('LINEAR', 'API', 'GITHUB')),
    source_external_id text NOT NULL,
    repository_id uuid,
    state text NOT NULL CHECK (state IN (
        'DISCOVERED',
        'READINESS_PENDING',
        'NEEDS_SPEC',
        'READY',
        'ACCEPTED',
        'PLANNED',
        'SCHEDULED',
        'DISPATCHING',
        'RUNNING',
        'VERIFYING_OUTCOME',
        'TARGET_REACHED',
        'CLOSING_SOURCE',
        'CLOSED',
        'WAITING_DEPENDENCY',
        'WAITING_APPROVAL',
        'RETRY_SCHEDULED',
        'BLOCKED_EXTERNAL',
        'BUDGET_EXHAUSTED',
        'REFUSED',
        'QUARANTINED',
        'CANCEL_REQUESTED',
        'CANCELLED',
        'ESCALATED'
    )),
    closure_target text CHECK (closure_target IN ('pull_request', 'merge', 'deploy', 'observe')),
    risk_class text CHECK (risk_class IN ('low', 'medium', 'high', 'critical', 'unknown')),
    risk_assessment jsonb CHECK (
        risk_assessment IS NULL OR jsonb_typeof(risk_assessment) = 'object'
    ),
    policy_digest text CHECK (
        policy_digest IS NULL OR policy_digest ~ '^sha256:[0-9a-f]{64}$'
    ),
    budget_limits jsonb CHECK (
        budget_limits IS NULL OR asf_valid_budget_limits(budget_limits)
    ),
    identity_requirements jsonb CHECK (
        identity_requirements IS NULL OR asf_valid_identity_requirements(identity_requirements)
    ),
    owner_fallback text,
    normalized_priority smallint NOT NULL CHECK (normalized_priority BETWEEN 0 AND 100),
    due_at timestamptz,
    current_attempt_id uuid,
    aggregate_version bigint NOT NULL DEFAULT 1 CHECK (aggregate_version > 0),
    discovered_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    ready_at timestamptz,
    accepted_at timestamptz,
    closed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, source_system, source_external_id),
    FOREIGN KEY (tenant_id, source_snapshot_id)
        REFERENCES source_snapshots(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, repository_id)
        REFERENCES repositories(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, policy_digest)
        REFERENCES policy_versions(tenant_id, digest) DEFERRABLE INITIALLY DEFERRED,
    CHECK (btrim(source_external_id) <> ''),
    CHECK (owner_fallback IS NULL OR btrim(owner_fallback) <> ''),
    CHECK (ready_at IS NULL OR ready_at >= discovered_at),
    CHECK (accepted_at IS NULL OR accepted_at >= discovered_at),
    CHECK (closed_at IS NULL OR accepted_at IS NOT NULL),
    CHECK (closed_at IS NULL OR closed_at >= accepted_at),
    CHECK (
        state IN (
            'DISCOVERED',
            'READINESS_PENDING',
            'NEEDS_SPEC',
            'READY',
            'WAITING_DEPENDENCY',
            'REFUSED'
        )
        OR accepted_at IS NOT NULL
    ),
    CHECK (state <> 'CLOSED' OR closed_at IS NOT NULL),
    CHECK (
        accepted_at IS NULL
        OR (
            repository_id IS NOT NULL
            AND closure_target IS NOT NULL
            AND risk_class IS NOT NULL
            AND policy_digest IS NOT NULL
            AND budget_limits IS NOT NULL
            AND identity_requirements IS NOT NULL
            AND owner_fallback IS NOT NULL
        )
    )
);

CREATE INDEX work_items_scheduler_idx
    ON work_items (tenant_id, normalized_priority DESC, ready_at, id)
    WHERE state IN ('READY', 'ACCEPTED', 'PLANNED', 'SCHEDULED', 'RETRY_SCHEDULED');

CREATE INDEX work_items_accountability_scan_idx
    ON work_items (tenant_id, state, updated_at)
    WHERE accepted_at IS NOT NULL;

COMMENT ON COLUMN work_items.closure_target IS
    'Internal normalized target; the public Work Order value `pr` maps to `pull_request`.';

CREATE TABLE plans (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid NOT NULL,
    plan_version bigint NOT NULL CHECK (plan_version > 0),
    status text NOT NULL CHECK (status IN ('PROPOSED', 'APPROVED', 'REJECTED', 'SUPERSEDED')),
    proposal jsonb NOT NULL CHECK (jsonb_typeof(proposal) = 'object'),
    proposal_digest text NOT NULL CHECK (proposal_digest ~ '^sha256:[0-9a-f]{64}$'),
    planner_digest text NOT NULL CHECK (planner_digest ~ '^sha256:[0-9a-f]{64}$'),
    created_by text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    decided_at timestamptz,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, work_item_id, plan_version),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(created_by) <> ''),
    CHECK (decided_at IS NULL OR decided_at >= created_at)
);

CREATE TABLE dependencies (
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid NOT NULL,
    depends_on_work_item_id uuid NOT NULL,
    dependency_type text NOT NULL DEFAULT 'BLOCKING'
        CHECK (dependency_type IN ('BLOCKING', 'INFORMATIONAL')),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (tenant_id, work_item_id, depends_on_work_item_id),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, depends_on_work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    CHECK (work_item_id <> depends_on_work_item_id)
);

CREATE TABLE workers (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    name text NOT NULL,
    endpoint text NOT NULL,
    status text NOT NULL DEFAULT 'REGISTERED'
        CHECK (status IN ('REGISTERED', 'READY', 'DRAINING', 'OFFLINE', 'QUARANTINED')),
    capabilities jsonb NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(capabilities) = 'object'),
    generation bigint NOT NULL DEFAULT 1 CHECK (generation > 0),
    max_concurrency integer NOT NULL DEFAULT 1 CHECK (max_concurrency > 0),
    signing_key_id text NOT NULL,
    signing_public_key text NOT NULL,
    last_seen_at timestamptz,
    aggregate_version bigint NOT NULL DEFAULT 1 CHECK (aggregate_version > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, name),
    UNIQUE (tenant_id, endpoint),
    CHECK (btrim(name) <> ''),
    CHECK (btrim(endpoint) <> ''),
    CHECK (btrim(signing_key_id) <> ''),
    CHECK (btrim(signing_public_key) <> '')
);

-- A worker generation is the restart/revocation epoch; a session is the
-- concrete, expiring connection within that epoch.  Runs and raw events retain
-- the session identity that admitted them, while ingestion also verifies that
-- the worker's current generation still matches.
CREATE TABLE worker_sessions (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    worker_id uuid NOT NULL,
    worker_generation bigint NOT NULL CHECK (worker_generation > 0),
    status text NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'CLOSED', 'REVOKED')),
    started_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    expires_at timestamptz NOT NULL,
    closed_at timestamptz,
    close_reason text,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, id, worker_id, worker_generation),
    FOREIGN KEY (tenant_id, worker_id)
        REFERENCES workers(tenant_id, id) ON DELETE RESTRICT,
    CHECK (expires_at > started_at),
    CHECK (close_reason IS NULL OR btrim(close_reason) <> ''),
    CHECK (
        (status = 'ACTIVE' AND closed_at IS NULL AND close_reason IS NULL)
        OR (status IN ('CLOSED', 'REVOKED') AND closed_at IS NOT NULL AND close_reason IS NOT NULL)
    ),
    CHECK (closed_at IS NULL OR closed_at >= started_at)
);

CREATE UNIQUE INDEX worker_sessions_one_active_per_worker_idx
    ON worker_sessions (tenant_id, worker_id)
    WHERE status = 'ACTIVE';

CREATE INDEX worker_sessions_expiry_idx
    ON worker_sessions (expires_at, id)
    WHERE status = 'ACTIVE';

CREATE TABLE attempts (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid NOT NULL,
    ordinal integer NOT NULL CHECK (ordinal > 0),
    state text NOT NULL CHECK (state IN (
        'CREATED',
        'AUTHORIZED',
        'DISPATCHING',
        'RUNNING',
        'VERIFYING',
        'WAITING_APPROVAL',
        'RETRYABLE_FAILED',
        'SUCCEEDED',
        'FAILED',
        'REFUSED',
        'CANCEL_REQUESTED',
        'CANCELLED',
        'QUARANTINED'
    )),
    idempotency_key text NOT NULL,
    base_ref text NOT NULL,
    base_sha text NOT NULL,
    source_snapshot_digest text NOT NULL CHECK (source_snapshot_digest ~ '^sha256:[0-9a-f]{64}$'),
    policy_digest text NOT NULL CHECK (policy_digest ~ '^sha256:[0-9a-f]{64}$'),
    work_order_digest text CHECK (
        work_order_digest IS NULL OR work_order_digest ~ '^sha256:[0-9a-f]{64}$'
    ),
    fence_token bigint NOT NULL DEFAULT 0 CHECK (fence_token >= 0),
    aggregate_version bigint NOT NULL DEFAULT 1 CHECK (aggregate_version > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    started_at timestamptz,
    terminal_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, id, work_item_id),
    UNIQUE (tenant_id, work_item_id, ordinal),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, policy_digest)
        REFERENCES policy_versions(tenant_id, digest) DEFERRABLE INITIALLY DEFERRED,
    CHECK (btrim(idempotency_key) <> ''),
    CHECK (btrim(base_ref) <> ''),
    CHECK (
        base_sha ~ '^[0-9a-f]+$'
        AND length(base_sha) IN (40, 64)
    ),
    CHECK (started_at IS NULL OR started_at >= created_at),
    CHECK (terminal_at IS NULL OR terminal_at >= created_at)
);

CREATE UNIQUE INDEX attempts_one_active_per_work_item_idx
    ON attempts (tenant_id, work_item_id)
    WHERE state IN (
        'CREATED',
        'AUTHORIZED',
        'DISPATCHING',
        'RUNNING',
        'VERIFYING',
        'WAITING_APPROVAL',
        'CANCEL_REQUESTED'
    );

ALTER TABLE work_items
    ADD CONSTRAINT work_items_current_attempt_fk
    FOREIGN KEY (tenant_id, current_attempt_id, id)
    REFERENCES attempts(tenant_id, id, work_item_id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE work_orders (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid NOT NULL,
    attempt_id uuid NOT NULL,
    schema_version text NOT NULL,
    envelope_schema text NOT NULL,
    algorithm text NOT NULL,
    key_id text NOT NULL,
    idempotency_key text NOT NULL,
    payload_digest text NOT NULL CHECK (payload_digest ~ '^sha256:[0-9a-f]{64}$'),
    canonical_payload bytea NOT NULL CHECK (octet_length(canonical_payload) > 0),
    payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
    signature text NOT NULL,
    exact_signed_envelope bytea NOT NULL CHECK (octet_length(exact_signed_envelope) > 0),
    issued_at timestamptz NOT NULL,
    not_before timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    stored_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, attempt_id),
    UNIQUE (tenant_id, payload_digest),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, attempt_id)
        REFERENCES attempts(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(schema_version) <> ''),
    CHECK (btrim(envelope_schema) <> ''),
    CHECK (btrim(algorithm) <> ''),
    CHECK (btrim(key_id) <> ''),
    CHECK (btrim(idempotency_key) <> ''),
    CHECK (btrim(signature) <> ''),
    CHECK (issued_at <= not_before),
    CHECK (not_before < expires_at)
);

ALTER TABLE attempts
    ADD CONSTRAINT attempts_work_order_digest_fk
    FOREIGN KEY (tenant_id, work_order_digest)
    REFERENCES work_orders(tenant_id, payload_digest)
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE runs (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid NOT NULL,
    attempt_id uuid NOT NULL,
    work_order_id uuid NOT NULL,
    worker_id uuid NOT NULL,
    worker_generation bigint NOT NULL CHECK (worker_generation > 0),
    worker_session_id uuid NOT NULL,
    evidence_expectation_digest text NOT NULL
        CHECK (evidence_expectation_digest ~ '^sha256:[0-9a-f]{64}$'),
    external_run_id text NOT NULL,
    authoritative boolean NOT NULL DEFAULT true,
    state text NOT NULL CHECK (state IN (
        'ADOPTED',
        'RUNNING',
        'WAITING_APPROVAL',
        'VERIFYING',
        'SUCCEEDED',
        'FAILED',
        'REFUSED',
        'CANCEL_REQUESTED',
        'CANCELLED',
        'QUARANTINED'
    )),
    last_event_cursor text,
    last_event_sequence bigint NOT NULL DEFAULT 0 CHECK (last_event_sequence >= 0),
    snapshot jsonb CHECK (snapshot IS NULL OR jsonb_typeof(snapshot) = 'object'),
    aggregate_version bigint NOT NULL DEFAULT 1 CHECK (aggregate_version > 0),
    adopted_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_observed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    terminal_at timestamptz,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, worker_id, external_run_id),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, attempt_id)
        REFERENCES attempts(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, work_order_id)
        REFERENCES work_orders(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, worker_id)
        REFERENCES workers(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, worker_session_id, worker_id, worker_generation)
        REFERENCES worker_sessions(tenant_id, id, worker_id, worker_generation)
        ON DELETE RESTRICT,
    CHECK (btrim(external_run_id) <> ''),
    CHECK (terminal_at IS NULL OR terminal_at >= adopted_at)
);

CREATE UNIQUE INDEX runs_one_authoritative_per_attempt_idx
    ON runs (tenant_id, attempt_id)
    WHERE authoritative;

CREATE TABLE raw_run_events (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    run_id uuid NOT NULL,
    worker_session_id uuid NOT NULL,
    worker_id uuid NOT NULL,
    worker_generation bigint NOT NULL CHECK (worker_generation > 0),
    external_event_id text NOT NULL,
    cursor text NOT NULL,
    sequence bigint NOT NULL CHECK (sequence > 0),
    run_aggregate_version bigint NOT NULL CHECK (run_aggregate_version > 0),
    schema_version text NOT NULL,
    event_type text NOT NULL,
    occurred_at timestamptz NOT NULL,
    ingested_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, id, run_id, run_aggregate_version),
    UNIQUE (tenant_id, run_id, external_event_id),
    UNIQUE (tenant_id, run_id, cursor),
    FOREIGN KEY (tenant_id, run_id)
        REFERENCES runs(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, worker_session_id, worker_id, worker_generation)
        REFERENCES worker_sessions(tenant_id, id, worker_id, worker_generation)
        ON DELETE RESTRICT,
    CHECK (btrim(external_event_id) <> ''),
    CHECK (btrim(cursor) <> ''),
    CHECK (btrim(schema_version) <> ''),
    CHECK (btrim(event_type) <> '')
);

CREATE INDEX raw_run_events_cursor_idx
    ON raw_run_events (tenant_id, run_id, sequence, ingested_at);

CREATE UNIQUE INDEX raw_run_events_sequence_idx
    ON raw_run_events (tenant_id, run_id, sequence);

CREATE TABLE run_event_applications (
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    run_event_id uuid NOT NULL,
    run_id uuid NOT NULL,
    run_aggregate_version bigint NOT NULL CHECK (run_aggregate_version > 0),
    applied_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (tenant_id, run_event_id),
    UNIQUE (tenant_id, run_id, run_aggregate_version),
    FOREIGN KEY (tenant_id, run_event_id, run_id, run_aggregate_version)
        REFERENCES raw_run_events(tenant_id, id, run_id, run_aggregate_version)
        ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, run_id)
        REFERENCES runs(tenant_id, id) ON DELETE RESTRICT
);

CREATE TABLE approvals (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid NOT NULL,
    attempt_id uuid,
    approval_type text NOT NULL,
    status text NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'REVOKED')),
    work_order_digest text,
    candidate_sha text,
    decision_effect_type text NOT NULL,
    risk_class text NOT NULL CHECK (risk_class IN ('low', 'medium', 'high', 'critical', 'unknown')),
    policy_digest text NOT NULL CHECK (policy_digest ~ '^sha256:[0-9a-f]{64}$'),
    evidence_digest text,
    owner_subject text NOT NULL,
    owner_role text NOT NULL,
    decision_subject text,
    decision_reason text,
    request_idempotency_key text NOT NULL,
    decision_idempotency_key text,
    aggregate_version bigint NOT NULL DEFAULT 1 CHECK (aggregate_version > 0),
    issued_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    expires_at timestamptz NOT NULL,
    decided_at timestamptz,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, request_idempotency_key),
    UNIQUE (tenant_id, decision_idempotency_key),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, attempt_id)
        REFERENCES attempts(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(approval_type) <> ''),
    CHECK (btrim(decision_effect_type) <> ''),
    CHECK (btrim(owner_subject) <> ''),
    CHECK (btrim(owner_role) <> ''),
    CHECK (btrim(request_idempotency_key) <> ''),
    CHECK (work_order_digest IS NULL OR work_order_digest ~ '^sha256:[0-9a-f]{64}$'),
    CHECK (evidence_digest IS NULL OR evidence_digest ~ '^sha256:[0-9a-f]{64}$'),
    CHECK (
        candidate_sha IS NULL
        OR (candidate_sha ~ '^[0-9a-f]+$' AND length(candidate_sha) IN (40, 64))
    ),
    CHECK (expires_at > issued_at),
    CHECK (decided_at IS NULL OR decided_at >= issued_at),
    CHECK (
        (status = 'PENDING' AND decided_at IS NULL)
        OR (status <> 'PENDING' AND decided_at IS NOT NULL)
    )
);

CREATE INDEX approvals_attention_idx
    ON approvals (tenant_id, expires_at, id)
    WHERE status = 'PENDING';

CREATE TABLE escalations (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid NOT NULL,
    attempt_id uuid,
    run_id uuid,
    category text NOT NULL CHECK (category IN (
        'NEEDS_SPEC',
        'NEEDS_APPROVAL',
        'BLOCKED_DEPENDENCY',
        'BLOCKED_EXTERNAL',
        'IDENTITY_UNAVAILABLE',
        'WORKER_UNAVAILABLE',
        'VERIFICATION_FAILED',
        'REVIEW_BLOCKED',
        'CI_FAILED',
        'REMOTE_EFFECT_AMBIGUOUS',
        'BUDGET_EXHAUSTED',
        'PROVIDER_REFUSED',
        'POLICY_REFUSED',
        'WORKFLOW_JOB_EXHAUSTED',
        'QUARANTINED',
        'SECURITY_INCIDENT'
    )),
    status text NOT NULL DEFAULT 'OPEN'
        CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'CANCELLED')),
    severity text NOT NULL CHECK (severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    reason text NOT NULL,
    owner_type text NOT NULL CHECK (owner_type IN ('PERSON', 'TEAM', 'ON_CALL')),
    owner_id text NOT NULL,
    required_action text NOT NULL,
    evidence_references jsonb NOT NULL DEFAULT '[]'::jsonb
        CHECK (jsonb_typeof(evidence_references) = 'array'),
    deadline timestamptz NOT NULL,
    escalation_path jsonb NOT NULL DEFAULT '[]'::jsonb
        CHECK (jsonb_typeof(escalation_path) = 'array'),
    retry_policy jsonb NOT NULL CHECK (jsonb_typeof(retry_policy) = 'object'),
    prerequisites jsonb NOT NULL DEFAULT '[]'::jsonb
        CHECK (jsonb_typeof(prerequisites) = 'array'),
    authority_or_effect_active boolean NOT NULL,
    idempotency_key text NOT NULL,
    aggregate_version bigint NOT NULL DEFAULT 1 CHECK (aggregate_version > 0),
    opened_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    acknowledged_at timestamptz,
    closed_at timestamptz,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, id, work_item_id),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, attempt_id)
        REFERENCES attempts(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, run_id)
        REFERENCES runs(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(reason) <> ''),
    CHECK (btrim(owner_id) <> ''),
    CHECK (btrim(required_action) <> ''),
    CHECK (btrim(idempotency_key) <> ''),
    CHECK (deadline > opened_at),
    CHECK (closed_at IS NULL OR closed_at >= opened_at)
);

CREATE UNIQUE INDEX escalations_one_open_category_idx
    ON escalations (
        tenant_id,
        work_item_id,
        COALESCE(attempt_id, '00000000-0000-0000-0000-000000000000'::uuid),
        category
    )
    WHERE status IN ('OPEN', 'ACKNOWLEDGED');

CREATE INDEX escalations_attention_idx
    ON escalations (tenant_id, severity DESC, deadline, id)
    WHERE status IN ('OPEN', 'ACKNOWLEDGED');

-- Tenant-scoped activities such as intake and worker reconciliation do not
-- belong to a synthetic work item. Their terminal failures still require the
-- same durable ownership and operator-attention guarantees as delivery work.
CREATE TABLE operational_incidents (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    workflow_job_id uuid NOT NULL,
    category text NOT NULL CHECK (category = 'WORKFLOW_JOB_EXHAUSTED'),
    status text NOT NULL DEFAULT 'OPEN'
        CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'CANCELLED')),
    severity text NOT NULL CHECK (severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    reason text NOT NULL,
    owner_type text NOT NULL CHECK (owner_type IN ('PERSON', 'TEAM', 'ON_CALL')),
    owner_id text NOT NULL,
    required_action text NOT NULL,
    evidence_references jsonb NOT NULL CHECK (jsonb_typeof(evidence_references) = 'array'),
    deadline timestamptz NOT NULL,
    escalation_path jsonb NOT NULL DEFAULT '[]'::jsonb
        CHECK (jsonb_typeof(escalation_path) = 'array'),
    retry_policy jsonb NOT NULL CHECK (jsonb_typeof(retry_policy) = 'object'),
    prerequisites jsonb NOT NULL DEFAULT '[]'::jsonb
        CHECK (jsonb_typeof(prerequisites) = 'array'),
    authority_or_effect_active boolean NOT NULL,
    idempotency_key text NOT NULL,
    aggregate_version bigint NOT NULL DEFAULT 1 CHECK (aggregate_version > 0),
    opened_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    acknowledged_at timestamptz,
    closed_at timestamptz,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, id, workflow_job_id),
    UNIQUE (tenant_id, workflow_job_id, category),
    UNIQUE (tenant_id, idempotency_key),
    CHECK (btrim(reason) <> ''),
    CHECK (btrim(owner_id) <> ''),
    CHECK (btrim(required_action) <> ''),
    CHECK (btrim(idempotency_key) <> ''),
    CHECK (jsonb_array_length(evidence_references) > 0),
    CHECK (deadline > opened_at),
    CHECK (acknowledged_at IS NULL OR acknowledged_at >= opened_at),
    CHECK (closed_at IS NULL OR closed_at >= opened_at)
);

CREATE INDEX operational_incidents_attention_idx
    ON operational_incidents (tenant_id, severity DESC, deadline, id)
    WHERE status IN ('OPEN', 'ACKNOWLEDGED');

CREATE TABLE evidence_bundles (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid NOT NULL,
    attempt_id uuid NOT NULL,
    run_id uuid NOT NULL,
    worker_id uuid NOT NULL,
    worker_generation bigint NOT NULL CHECK (worker_generation > 0),
    schema_version text NOT NULL,
    envelope_schema text NOT NULL,
    algorithm text NOT NULL,
    key_id text NOT NULL,
    payload_digest text NOT NULL CHECK (payload_digest ~ '^sha256:[0-9a-f]{64}$'),
    work_order_digest text NOT NULL CHECK (work_order_digest ~ '^sha256:[0-9a-f]{64}$'),
    base_sha text NOT NULL,
    candidate_sha text NOT NULL,
    requested_target text NOT NULL CHECK (requested_target IN ('pull_request', 'merge', 'deploy', 'observe')),
    target_satisfied boolean NOT NULL,
    canonical_payload bytea NOT NULL CHECK (octet_length(canonical_payload) > 0),
    payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
    signature text NOT NULL,
    exact_signed_envelope bytea NOT NULL CHECK (octet_length(exact_signed_envelope) > 0),
    produced_at timestamptz NOT NULL,
    stored_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, run_id, payload_digest),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, attempt_id)
        REFERENCES attempts(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, run_id)
        REFERENCES runs(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, worker_id)
        REFERENCES workers(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(schema_version) <> ''),
    CHECK (btrim(envelope_schema) <> ''),
    CHECK (btrim(algorithm) <> ''),
    CHECK (btrim(key_id) <> ''),
    CHECK (btrim(signature) <> ''),
    CHECK (base_sha ~ '^[0-9a-f]+$' AND length(base_sha) IN (40, 64)),
    CHECK (candidate_sha ~ '^[0-9a-f]+$' AND length(candidate_sha) IN (40, 64))
);

CREATE TABLE evidence_verifications (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    evidence_id uuid NOT NULL,
    verifier text NOT NULL,
    status text NOT NULL CHECK (status IN ('VALID', 'INVALID', 'INCONCLUSIVE')),
    expectation_digest text NOT NULL CHECK (expectation_digest ~ '^sha256:[0-9a-f]{64}$'),
    details jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(details) = 'object'),
    verified_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, evidence_id, expectation_digest),
    FOREIGN KEY (tenant_id, evidence_id)
        REFERENCES evidence_bundles(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(verifier) <> '')
);

COMMENT ON COLUMN evidence_bundles.requested_target IS
    'Internal normalized target; the public evidence value `pr` maps to `pull_request`.';

CREATE TABLE artifacts (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    digest_algorithm text NOT NULL DEFAULT 'sha256' CHECK (digest_algorithm IN ('sha256', 'blake3')),
    digest text NOT NULL,
    media_type text NOT NULL,
    byte_size bigint NOT NULL CHECK (byte_size >= 0),
    object_key text NOT NULL,
    encryption_class text NOT NULL,
    retention_class text NOT NULL,
    access_policy text NOT NULL,
    producer text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    expires_at timestamptz,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, digest_algorithm, digest),
    UNIQUE (tenant_id, object_key),
    CHECK (btrim(media_type) <> ''),
    CHECK (btrim(object_key) <> ''),
    CHECK (btrim(encryption_class) <> ''),
    CHECK (btrim(retention_class) <> ''),
    CHECK (btrim(access_policy) <> ''),
    CHECK (btrim(producer) <> ''),
    CHECK (
        (digest_algorithm = 'sha256' AND digest ~ '^sha256:[0-9a-f]{64}$')
        OR (digest_algorithm = 'blake3' AND digest ~ '^blake3:[0-9a-f]{64}$')
    ),
    CHECK (expires_at IS NULL OR expires_at > created_at)
);

CREATE TABLE evidence_artifacts (
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    evidence_id uuid NOT NULL,
    artifact_id uuid NOT NULL,
    relationship text NOT NULL CHECK (relationship IN ('LOG', 'DIFF', 'CHECK_REPORT', 'REVIEW_REPORT', 'PROVENANCE', 'TRANSCRIPT', 'OTHER')),
    PRIMARY KEY (tenant_id, evidence_id, artifact_id),
    FOREIGN KEY (tenant_id, evidence_id)
        REFERENCES evidence_bundles(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, artifact_id)
        REFERENCES artifacts(tenant_id, id) ON DELETE RESTRICT
);

-- Non-secret ctxlane profile references are capacity resources. Credentials,
-- execution handles, and vendor state never belong in this table.
CREATE TABLE identity_capacity_limits (
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    profile_ref text NOT NULL,
    capacity bigint NOT NULL CHECK (capacity > 0),
    generation bigint NOT NULL DEFAULT 1 CHECK (generation > 0),
    enabled boolean NOT NULL DEFAULT true,
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (tenant_id, profile_ref),
    CHECK (profile_ref ~ '^(claude|codex):[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')
);

-- One admission set is the all-or-nothing ownership boundary for repository,
-- worker, identity, and multidimensional budget capacity.
CREATE TABLE reservation_sets (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid NOT NULL,
    attempt_id uuid NOT NULL,
    repository_id uuid NOT NULL,
    worker_id uuid NOT NULL,
    request_digest text NOT NULL CHECK (request_digest ~ '^sha256:[0-9a-f]{64}$'),
    idempotency_key text NOT NULL,
    state text NOT NULL DEFAULT 'ACTIVE'
        CHECK (state IN ('ACTIVE', 'RELEASED', 'EXPIRED')),
    fence_token bigint NOT NULL DEFAULT 1 CHECK (fence_token > 0),
    acquired_by text NOT NULL,
    acquired_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    expires_at timestamptz NOT NULL,
    released_at timestamptz,
    released_by text,
    release_reason text,
    transition_idempotency_key text,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, id, work_item_id, attempt_id),
    UNIQUE (tenant_id, idempotency_key),
    UNIQUE (tenant_id, transition_idempotency_key),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, attempt_id, work_item_id)
        REFERENCES attempts(tenant_id, id, work_item_id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, repository_id)
        REFERENCES repositories(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, worker_id)
        REFERENCES workers(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(idempotency_key) <> ''),
    -- `asf-internal:` is reserved for deterministic control-plane operations.
    -- Admission keys are always caller supplied and may never enter it.
    CHECK (idempotency_key NOT LIKE 'asf-internal:%'),
    CHECK (btrim(acquired_by) <> ''),
    CHECK (expires_at > acquired_at),
    CHECK (
        (state = 'ACTIVE'
            AND released_at IS NULL
            AND released_by IS NULL
            AND release_reason IS NULL
            AND transition_idempotency_key IS NULL)
        OR (state <> 'ACTIVE'
            AND released_at IS NOT NULL
            AND released_by IS NOT NULL
            AND release_reason IS NOT NULL
            AND transition_idempotency_key IS NOT NULL)
    ),
    CHECK (released_by IS NULL OR btrim(released_by) <> ''),
    CHECK (release_reason IS NULL OR btrim(release_reason) <> ''),
    CHECK (transition_idempotency_key IS NULL OR btrim(transition_idempotency_key) <> ''),
    CHECK (
        transition_idempotency_key IS NULL
        OR transition_idempotency_key NOT LIKE 'asf-internal:%'
        OR (
            state = 'EXPIRED'
            AND transition_idempotency_key =
                'asf-internal:reservation-expiry:v1:' || id::text
                || ':fence:' || (fence_token - 1)::text
        )
    )
);

CREATE TABLE reservations (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    reservation_set_id uuid NOT NULL,
    kind text NOT NULL CHECK (kind IN ('REPOSITORY_WIP', 'WORKER_SLOT', 'IDENTITY_CAPACITY', 'BUDGET')),
    resource_key text NOT NULL,
    budget_dimension text CHECK (budget_dimension IN (
        'COST_MICROUNITS',
        'INPUT_TOKENS',
        'OUTPUT_TOKENS',
        'IMPLEMENTER_INVOCATIONS',
        'REVIEWER_INVOCATIONS',
        'FIX_ITERATIONS',
        'WALL_TIME_SECONDS',
        'EXTERNAL_API_CALLS'
    )),
    units bigint NOT NULL CHECK (units >= 0),
    idempotency_key text NOT NULL,
    resource_generation bigint NOT NULL DEFAULT 1 CHECK (resource_generation > 0),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, idempotency_key),
    UNIQUE (tenant_id, reservation_set_id, kind, resource_key),
    FOREIGN KEY (tenant_id, reservation_set_id)
        REFERENCES reservation_sets(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(idempotency_key) <> ''),
    CHECK (idempotency_key NOT LIKE 'asf-internal:%'),
    CHECK (btrim(resource_key) <> ''),
    CHECK ((kind = 'BUDGET') = (budget_dimension IS NOT NULL)),
    CHECK (kind = 'BUDGET' OR units > 0)
);

CREATE INDEX reservations_resource_capacity_idx
    ON reservations (tenant_id, kind, resource_key, reservation_set_id);

CREATE INDEX reservation_sets_expiry_idx
    ON reservation_sets (tenant_id, expires_at, id)
    WHERE state = 'ACTIVE';

CREATE UNIQUE INDEX reservation_sets_one_active_per_attempt_idx
    ON reservation_sets (tenant_id, attempt_id)
    WHERE state = 'ACTIVE';

CREATE TABLE reservation_set_events (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    reservation_set_id uuid NOT NULL,
    event_type text NOT NULL CHECK (event_type IN ('ACQUIRED', 'RELEASED', 'EXPIRED')),
    previous_fence_token bigint NOT NULL CHECK (previous_fence_token >= 0),
    fence_token bigint NOT NULL CHECK (fence_token > 0),
    actor_id text NOT NULL,
    reason text NOT NULL,
    idempotency_key text NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, reservation_set_id)
        REFERENCES reservation_sets(tenant_id, id) ON DELETE RESTRICT,
    CHECK (fence_token = previous_fence_token + 1),
    CHECK (btrim(actor_id) <> ''),
    CHECK (btrim(reason) <> ''),
    CHECK (btrim(idempotency_key) <> ''),
    -- Internal expiry events are self-scoped by set ID and prior fence. This
    -- makes their tenant-global idempotency keys impossible to pre-occupy from
    -- another reservation set even if application validation is bypassed.
    CHECK (
        idempotency_key NOT LIKE 'asf-internal:%'
        OR (
            event_type = 'EXPIRED'
            AND idempotency_key =
                'asf-internal:reservation-expiry:v1:' || reservation_set_id::text
                || ':fence:' || previous_fence_token::text
        )
    )
);

CREATE TABLE budget_ledger (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid,
    attempt_id uuid,
    reservation_id uuid,
    scope_type text NOT NULL CHECK (scope_type IN ('TENANT', 'REPOSITORY', 'WORKER', 'PROVIDER', 'MODEL', 'WORK_CLASS', 'ATTEMPT')),
    scope_id text NOT NULL,
    dimension text NOT NULL CHECK (dimension IN (
        'COST_MICROUNITS',
        'INPUT_TOKENS',
        'OUTPUT_TOKENS',
        'IMPLEMENTER_INVOCATIONS',
        'REVIEWER_INVOCATIONS',
        'FIX_ITERATIONS',
        'WALL_TIME_SECONDS',
        'EXTERNAL_API_CALLS'
    )),
    entry_type text NOT NULL CHECK (entry_type IN ('RESERVE', 'CONSUME', 'RELEASE', 'ADJUST')),
    amount bigint NOT NULL CHECK (amount >= 0),
    unit text NOT NULL,
    currency text,
    idempotency_key text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
    occurred_at timestamptz NOT NULL,
    recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, attempt_id)
        REFERENCES attempts(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, reservation_id)
        REFERENCES reservations(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(scope_id) <> ''),
    CHECK (btrim(unit) <> ''),
    CHECK (btrim(idempotency_key) <> ''),
    CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$')
);

CREATE INDEX budget_ledger_scope_idx
    ON budget_ledger (tenant_id, scope_type, scope_id, dimension, occurred_at);

CREATE TABLE workflow_instances (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid NOT NULL,
    workflow_type text NOT NULL,
    state text NOT NULL DEFAULT 'ACTIVE'
        CHECK (state IN ('ACTIVE', 'WAITING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    reducer_version text NOT NULL,
    event_cursor bigint NOT NULL DEFAULT 0 CHECK (event_cursor >= 0),
    fence_token bigint NOT NULL DEFAULT 0 CHECK (fence_token >= 0),
    aggregate_version bigint NOT NULL DEFAULT 1 CHECK (aggregate_version > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    terminal_at timestamptz,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, id, work_item_id),
    UNIQUE (tenant_id, work_item_id, workflow_type),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(workflow_type) <> ''),
    CHECK (btrim(reducer_version) <> ''),
    CHECK (
        (state IN ('COMPLETED', 'FAILED', 'CANCELLED') AND terminal_at IS NOT NULL)
        OR (state IN ('ACTIVE', 'WAITING') AND terminal_at IS NULL)
    )
);

CREATE TABLE workflow_jobs (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    workflow_instance_id uuid,
    work_item_id uuid,
    attempt_id uuid,
    job_type text NOT NULL,
    status text NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'RUNNING', 'RETRY', 'COMPLETED', 'DEAD', 'CANCELLED')),
    priority smallint NOT NULL DEFAULT 0,
    payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
    result jsonb CHECK (result IS NULL OR jsonb_typeof(result) IN ('object', 'array', 'string', 'number', 'boolean', 'null')),
    idempotency_key text NOT NULL,
    available_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    max_attempts integer NOT NULL DEFAULT 25 CHECK (max_attempts > 0),
    fence_token bigint NOT NULL DEFAULT 0 CHECK (fence_token >= 0),
    lease_owner text,
    lease_expires_at timestamptz,
    completed_by text,
    completion_fence_token bigint,
    completed_at timestamptz,
    last_failure_by text,
    last_failure_fence_token bigint,
    last_failure_retry_at timestamptz,
    last_error text CHECK (last_error IS NULL OR length(last_error) <= 8192),
    dead_letter_escalation_id uuid,
    dead_letter_operational_incident_id uuid,
    dead_lettered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, workflow_instance_id, work_item_id)
        REFERENCES workflow_instances(tenant_id, id, work_item_id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, attempt_id)
        REFERENCES attempts(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, dead_letter_escalation_id, work_item_id)
        REFERENCES escalations(tenant_id, id, work_item_id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, dead_letter_operational_incident_id, id)
        REFERENCES operational_incidents(tenant_id, id, workflow_job_id) ON DELETE RESTRICT,
    CHECK (btrim(job_type) <> ''),
    CHECK (btrim(idempotency_key) <> ''),
    CHECK (workflow_instance_id IS NULL OR work_item_id IS NOT NULL),
    CHECK (
        (status = 'RUNNING' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
        OR (status <> 'RUNNING' AND lease_owner IS NULL AND lease_expires_at IS NULL)
    ),
    CHECK (
        (status = 'COMPLETED' AND completed_by IS NOT NULL AND completion_fence_token IS NOT NULL AND completed_at IS NOT NULL)
        OR status <> 'COMPLETED'
    ),
    CHECK (
        (
            status = 'DEAD'
            AND work_item_id IS NOT NULL
            AND dead_letter_escalation_id IS NOT NULL
            AND dead_letter_operational_incident_id IS NULL
            AND dead_lettered_at IS NOT NULL
        )
        OR (
            status = 'DEAD'
            AND workflow_instance_id IS NULL
            AND work_item_id IS NULL
            AND attempt_id IS NULL
            AND dead_letter_escalation_id IS NULL
            AND dead_letter_operational_incident_id IS NOT NULL
            AND dead_lettered_at IS NOT NULL
        )
        OR (
            status <> 'DEAD'
            AND dead_letter_escalation_id IS NULL
            AND dead_letter_operational_incident_id IS NULL
            AND dead_lettered_at IS NULL
        )
    )
);

ALTER TABLE operational_incidents
    ADD CONSTRAINT operational_incidents_workflow_job_fk
    FOREIGN KEY (tenant_id, workflow_job_id)
    REFERENCES workflow_jobs(tenant_id, id) ON DELETE RESTRICT;

CREATE INDEX workflow_jobs_claim_idx
    ON workflow_jobs (priority DESC, available_at, id)
    WHERE status IN ('PENDING', 'RETRY');

CREATE INDEX workflow_jobs_expired_lease_idx
    ON workflow_jobs (lease_expires_at, id)
    WHERE status = 'RUNNING';

CREATE TABLE workflow_timers (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    workflow_instance_id uuid,
    work_item_id uuid,
    attempt_id uuid,
    workflow_key text NOT NULL,
    timer_key text NOT NULL,
    timer_type text NOT NULL,
    status text NOT NULL DEFAULT 'SCHEDULED'
        CHECK (status IN ('SCHEDULED', 'FIRED', 'CANCELLED')),
    due_at timestamptz NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(payload) = 'object'),
    generation bigint NOT NULL DEFAULT 1 CHECK (generation > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    fired_at timestamptz,
    cancelled_at timestamptz,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, workflow_key, timer_key),
    FOREIGN KEY (tenant_id, workflow_instance_id, work_item_id)
        REFERENCES workflow_instances(tenant_id, id, work_item_id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, attempt_id)
        REFERENCES attempts(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(workflow_key) <> ''),
    CHECK (btrim(timer_key) <> ''),
    CHECK (btrim(timer_type) <> ''),
    CHECK (workflow_instance_id IS NULL OR work_item_id IS NOT NULL),
    CHECK (fired_at IS NULL OR fired_at >= created_at),
    CHECK (cancelled_at IS NULL OR cancelled_at >= created_at)
);

CREATE INDEX workflow_timers_due_idx
    ON workflow_timers (due_at, id)
    WHERE status = 'SCHEDULED';

CREATE TABLE effect_intents (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid,
    attempt_id uuid,
    provider text NOT NULL,
    effect_type text NOT NULL,
    status text NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'IN_FLIGHT', 'OBSERVED', 'AMBIGUOUS', 'FAILED', 'CANCELLED')),
    idempotency_key text NOT NULL,
    correlation_marker text,
    request_digest text NOT NULL CHECK (request_digest ~ '^sha256:[0-9a-f]{64}$'),
    request_payload jsonb NOT NULL CHECK (jsonb_typeof(request_payload) = 'object'),
    observed_outcome jsonb CHECK (observed_outcome IS NULL OR jsonb_typeof(observed_outcome) = 'object'),
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    fence_token bigint NOT NULL DEFAULT 0 CHECK (fence_token >= 0),
    lease_owner text,
    lease_expires_at timestamptz,
    last_error text CHECK (last_error IS NULL OR length(last_error) <= 8192),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    observed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, attempt_id)
        REFERENCES attempts(tenant_id, id) ON DELETE RESTRICT,
    CHECK (btrim(provider) <> ''),
    CHECK (btrim(effect_type) <> ''),
    CHECK (btrim(idempotency_key) <> ''),
    CHECK (
        (status = 'IN_FLIGHT' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
        OR (status <> 'IN_FLIGHT' AND lease_owner IS NULL AND lease_expires_at IS NULL)
    )
);

CREATE UNIQUE INDEX effect_intents_correlation_idx
    ON effect_intents (tenant_id, provider, correlation_marker)
    WHERE correlation_marker IS NOT NULL;

-- An authoritative attempt has at most one Runmill cancellation mutation.
-- The request body and external run identity remain immutable in that row;
-- replacement workflow jobs may only adopt it after a retryable outcome.
CREATE UNIQUE INDEX effect_intents_one_runmill_cancellation_per_attempt_idx
    ON effect_intents (tenant_id, work_item_id, attempt_id)
    WHERE provider = 'runmill'
      AND effect_type = 'request_cancellation'
      AND work_item_id IS NOT NULL
      AND attempt_id IS NOT NULL;

CREATE INDEX effect_intents_claim_idx
    ON effect_intents (next_attempt_at, id)
    WHERE status IN ('PENDING', 'AMBIGUOUS');

CREATE INDEX effect_intents_expired_lease_idx
    ON effect_intents (lease_expires_at, id)
    WHERE status = 'IN_FLIGHT';

CREATE TABLE outbox (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    topic text NOT NULL,
    message_key text NOT NULL,
    event_type text NOT NULL,
    payload jsonb NOT NULL,
    headers jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(headers) = 'object'),
    idempotency_key text NOT NULL,
    status text NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'PUBLISHING', 'PUBLISHED', 'RETRY', 'DEAD')),
    available_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    fence_token bigint NOT NULL DEFAULT 0 CHECK (fence_token >= 0),
    lease_owner text,
    lease_expires_at timestamptz,
    last_error text CHECK (last_error IS NULL OR length(last_error) <= 8192),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    published_at timestamptz,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, idempotency_key),
    CHECK (btrim(topic) <> ''),
    CHECK (btrim(message_key) <> ''),
    CHECK (btrim(event_type) <> ''),
    CHECK (btrim(idempotency_key) <> ''),
    CHECK (
        (status = 'PUBLISHING' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
        OR (status <> 'PUBLISHING' AND lease_owner IS NULL AND lease_expires_at IS NULL)
    )
);

CREATE INDEX outbox_claim_idx
    ON outbox (available_at, id)
    WHERE status IN ('PENDING', 'RETRY');

CREATE INDEX outbox_expired_lease_idx
    ON outbox (lease_expires_at, id)
    WHERE status = 'PUBLISHING';

CREATE TABLE audit_events (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid,
    attempt_id uuid,
    actor_type text NOT NULL,
    actor_id text NOT NULL,
    action text NOT NULL,
    subject_type text NOT NULL,
    subject_id text NOT NULL,
    correlation_id text NOT NULL,
    trace_id text,
    policy_digest text,
    before_digest text,
    after_digest text,
    previous_event_hash text,
    event_hash text NOT NULL CHECK (event_hash ~ '^sha256:[0-9a-f]{64}$'),
    details jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(details) = 'object'),
    occurred_at timestamptz NOT NULL,
    ingested_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, event_hash),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, attempt_id)
        REFERENCES attempts(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, previous_event_hash)
        REFERENCES audit_events(tenant_id, event_hash)
        DEFERRABLE INITIALLY DEFERRED,
    CHECK (btrim(actor_type) <> ''),
    CHECK (btrim(actor_id) <> ''),
    CHECK (btrim(action) <> ''),
    CHECK (btrim(subject_type) <> ''),
    CHECK (btrim(subject_id) <> ''),
    CHECK (btrim(correlation_id) <> ''),
    CHECK (policy_digest IS NULL OR policy_digest ~ '^sha256:[0-9a-f]{64}$'),
    CHECK (before_digest IS NULL OR before_digest ~ '^sha256:[0-9a-f]{64}$'),
    CHECK (after_digest IS NULL OR after_digest ~ '^sha256:[0-9a-f]{64}$'),
    CHECK (previous_event_hash IS NULL OR previous_event_hash ~ '^sha256:[0-9a-f]{64}$')
);

CREATE INDEX audit_events_subject_idx
    ON audit_events (tenant_id, subject_type, subject_id, occurred_at, id);

CREATE UNIQUE INDEX audit_events_one_root_per_tenant_idx
    ON audit_events (tenant_id)
    WHERE previous_event_hash IS NULL;

CREATE UNIQUE INDEX audit_events_one_successor_idx
    ON audit_events (tenant_id, previous_event_hash)
    WHERE previous_event_hash IS NOT NULL;

CREATE TABLE accountability_anchors (
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    work_item_id uuid NOT NULL,
    anchor_type text NOT NULL CHECK (anchor_type IN (
        'WORKFLOW',
        'RUN',
        'TIMER',
        'RETRY',
        'APPROVAL',
        'ESCALATION',
        'CLOSURE',
        'CANCELLATION'
    )),
    reference_id uuid NOT NULL,
    wake_or_deadline_at timestamptz,
    authority_or_effect_active boolean NOT NULL DEFAULT false,
    generation bigint NOT NULL DEFAULT 1 CHECK (generation > 0),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (tenant_id, work_item_id),
    FOREIGN KEY (tenant_id, work_item_id)
        REFERENCES work_items(tenant_id, id) ON DELETE RESTRICT,
    CHECK (
        (anchor_type IN ('TIMER', 'RETRY', 'APPROVAL', 'ESCALATION')
            AND wake_or_deadline_at IS NOT NULL)
        OR (anchor_type NOT IN ('TIMER', 'RETRY', 'APPROVAL', 'ESCALATION')
            AND wake_or_deadline_at IS NULL)
    )
);

CREATE TABLE circuit_breakers (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    scope_type text NOT NULL CHECK (scope_type IN ('TENANT', 'REPOSITORY', 'WORKER', 'PROVIDER', 'MODEL', 'WORK_CLASS')),
    scope_id text NOT NULL,
    breaker_type text NOT NULL,
    state text NOT NULL DEFAULT 'CLOSED' CHECK (state IN ('CLOSED', 'OPEN', 'HALF_OPEN')),
    reason text,
    metrics jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metrics) = 'object'),
    generation bigint NOT NULL DEFAULT 1 CHECK (generation > 0),
    aggregate_version bigint NOT NULL DEFAULT 1 CHECK (aggregate_version > 0),
    opened_at timestamptz,
    retry_after timestamptz,
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, scope_type, scope_id, breaker_type),
    CHECK (btrim(scope_id) <> ''),
    CHECK (btrim(breaker_type) <> ''),
    CHECK ((state = 'CLOSED') OR (opened_at IS NOT NULL AND reason IS NOT NULL)),
    CHECK (reason IS NULL OR btrim(reason) <> '')
);

CREATE INDEX circuit_breakers_open_idx
    ON circuit_breakers (tenant_id, scope_type, retry_after)
    WHERE state <> 'CLOSED';

CREATE TABLE idempotency_records (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    actor_id text NOT NULL,
    operation text NOT NULL,
    idempotency_key text NOT NULL,
    request_digest text NOT NULL CHECK (request_digest ~ '^sha256:[0-9a-f]{64}$'),
    state text NOT NULL DEFAULT 'IN_PROGRESS'
        CHECK (state IN ('IN_PROGRESS', 'COMPLETED', 'FAILED')),
    response_status integer CHECK (response_status IS NULL OR response_status BETWEEN 100 AND 599),
    response_body jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at timestamptz,
    expires_at timestamptz NOT NULL,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, actor_id, operation, idempotency_key),
    CHECK (btrim(actor_id) <> ''),
    CHECK (btrim(operation) <> ''),
    CHECK (btrim(idempotency_key) <> ''),
    CHECK (expires_at > created_at),
    CHECK (
        (state = 'IN_PROGRESS' AND completed_at IS NULL)
        OR (state <> 'IN_PROGRESS' AND completed_at IS NOT NULL)
    )
);

CREATE INDEX idempotency_records_expiry_idx
    ON idempotency_records (expires_at, id);

-- Immutable authority/evidence and append-only ledgers must be corrected by
-- supplemental records, never by UPDATE or DELETE.
CREATE FUNCTION asf_reject_row_mutation() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% is append-only; write a supplemental record instead', TG_TABLE_NAME
        USING ERRCODE = '55000';
END;
$$;

-- Effect execution may advance status, leases, retry accounting, and observed
-- outcomes, but it must never rewrite which logical request the row denotes.
CREATE FUNCTION asf_guard_effect_intent_update() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'effect intents cannot be deleted'
            USING ERRCODE = '23514',
                  CONSTRAINT = 'effect_intents_identity_request_immutable';
    END IF;
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
       OR NEW.work_item_id IS DISTINCT FROM OLD.work_item_id
       OR NEW.attempt_id IS DISTINCT FROM OLD.attempt_id
       OR NEW.provider IS DISTINCT FROM OLD.provider
       OR NEW.effect_type IS DISTINCT FROM OLD.effect_type
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
       OR NEW.correlation_marker IS DISTINCT FROM OLD.correlation_marker
       OR NEW.request_digest IS DISTINCT FROM OLD.request_digest
       OR NEW.request_payload IS DISTINCT FROM OLD.request_payload
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'effect intent identity and request are immutable'
            USING ERRCODE = '23514',
                  CONSTRAINT = 'effect_intents_identity_request_immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER effect_intents_identity_request_immutable
    BEFORE UPDATE OR DELETE ON effect_intents
    FOR EACH ROW EXECUTE FUNCTION asf_guard_effect_intent_update();

CREATE TRIGGER source_snapshots_immutable
    BEFORE UPDATE OR DELETE ON source_snapshots
    FOR EACH ROW EXECUTE FUNCTION asf_reject_row_mutation();

CREATE TRIGGER policy_versions_immutable
    BEFORE UPDATE OR DELETE ON policy_versions
    FOR EACH ROW EXECUTE FUNCTION asf_reject_row_mutation();

CREATE TRIGGER work_orders_immutable
    BEFORE UPDATE OR DELETE ON work_orders
    FOR EACH ROW EXECUTE FUNCTION asf_reject_row_mutation();

CREATE TRIGGER raw_run_events_immutable
    BEFORE UPDATE OR DELETE ON raw_run_events
    FOR EACH ROW EXECUTE FUNCTION asf_reject_row_mutation();

CREATE TRIGGER evidence_bundles_immutable
    BEFORE UPDATE OR DELETE ON evidence_bundles
    FOR EACH ROW EXECUTE FUNCTION asf_reject_row_mutation();

CREATE TRIGGER evidence_verifications_append_only
    BEFORE UPDATE OR DELETE ON evidence_verifications
    FOR EACH ROW EXECUTE FUNCTION asf_reject_row_mutation();

CREATE TRIGGER budget_ledger_append_only
    BEFORE UPDATE OR DELETE ON budget_ledger
    FOR EACH ROW EXECUTE FUNCTION asf_reject_row_mutation();

CREATE TRIGGER reservations_immutable
    BEFORE UPDATE OR DELETE ON reservations
    FOR EACH ROW EXECUTE FUNCTION asf_reject_row_mutation();

CREATE TRIGGER reservation_set_events_append_only
    BEFORE UPDATE OR DELETE ON reservation_set_events
    FOR EACH ROW EXECUTE FUNCTION asf_reject_row_mutation();

CREATE FUNCTION asf_guard_reservation_set_update() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
       OR NEW.work_item_id IS DISTINCT FROM OLD.work_item_id
       OR NEW.attempt_id IS DISTINCT FROM OLD.attempt_id
       OR NEW.repository_id IS DISTINCT FROM OLD.repository_id
       OR NEW.worker_id IS DISTINCT FROM OLD.worker_id
       OR NEW.request_digest IS DISTINCT FROM OLD.request_digest
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
       OR NEW.acquired_by IS DISTINCT FROM OLD.acquired_by
       OR NEW.acquired_at IS DISTINCT FROM OLD.acquired_at
       OR NEW.expires_at IS DISTINCT FROM OLD.expires_at THEN
        RAISE EXCEPTION 'reservation-set admission semantics are immutable'
            USING ERRCODE = '55000';
    END IF;
    IF OLD.state <> 'ACTIVE'
       OR NEW.state NOT IN ('RELEASED', 'EXPIRED')
       OR NEW.fence_token <> OLD.fence_token + 1 THEN
        RAISE EXCEPTION 'reservation-set transition is stale or invalid'
            USING ERRCODE = '40001';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER reservation_sets_fenced_update
    BEFORE UPDATE ON reservation_sets
    FOR EACH ROW EXECUTE FUNCTION asf_guard_reservation_set_update();

CREATE TRIGGER reservation_sets_cannot_be_deleted
    BEFORE DELETE ON reservation_sets
    FOR EACH ROW EXECUTE FUNCTION asf_reject_row_mutation();

-- Caller-controlled budget writers share a tenant-global idempotency index
-- with reservation release entries.  An ASF-internal key is valid only for
-- the exact budget reservation released by the matching expired set/fence;
-- otherwise a forged key could pre-occupy a future sweep and starve expiry.
CREATE FUNCTION asf_guard_internal_budget_ledger_key() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    bound_set_id uuid;
    bound_work_item_id uuid;
    bound_attempt_id uuid;
    bound_dimension text;
    bound_units bigint;
    bound_set_state text;
    bound_set_fence bigint;
    bound_transition_key text;
    bound_released_at timestamptz;
    expected_transition_key text;
    expected_budget_key text;
BEGIN
    IF NEW.idempotency_key NOT LIKE 'asf-internal:%' THEN
        RETURN NEW;
    END IF;

    SELECT
        reservation_set.id,
        reservation_set.work_item_id,
        reservation_set.attempt_id,
        reservation.budget_dimension,
        reservation.units,
        reservation_set.state,
        reservation_set.fence_token,
        reservation_set.transition_idempotency_key,
        reservation_set.released_at
    INTO
        bound_set_id,
        bound_work_item_id,
        bound_attempt_id,
        bound_dimension,
        bound_units,
        bound_set_state,
        bound_set_fence,
        bound_transition_key,
        bound_released_at
    FROM reservations AS reservation
    JOIN reservation_sets AS reservation_set
      ON reservation_set.tenant_id = reservation.tenant_id
     AND reservation_set.id = reservation.reservation_set_id
    WHERE reservation.tenant_id = NEW.tenant_id
      AND reservation.id = NEW.reservation_id
      AND reservation.kind = 'BUDGET';

    IF NOT FOUND THEN
        RAISE EXCEPTION 'ASF-internal budget key has no exact budget reservation binding'
            USING ERRCODE = '23514';
    END IF;

    expected_transition_key :=
        'asf-internal:reservation-expiry:v1:' || bound_set_id::text
        || ':fence:' || (bound_set_fence - 1)::text;
    expected_budget_key :=
        expected_transition_key || ':budget-release:' || bound_dimension;

    IF bound_set_state <> 'EXPIRED'
       OR bound_transition_key IS DISTINCT FROM expected_transition_key
       OR NEW.idempotency_key <> expected_budget_key
       OR NEW.entry_type <> 'RELEASE'
       OR NEW.work_item_id IS DISTINCT FROM bound_work_item_id
       OR NEW.attempt_id IS DISTINCT FROM bound_attempt_id
       OR NEW.scope_type <> 'ATTEMPT'
       OR NEW.scope_id <> bound_attempt_id::text
       OR NEW.dimension <> bound_dimension
       OR NEW.amount <> bound_units
       OR NEW.occurred_at IS DISTINCT FROM bound_released_at THEN
        RAISE EXCEPTION 'ASF-internal budget release key contradicts its reservation set/fence'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER budget_ledger_internal_key_guard
    BEFORE INSERT ON budget_ledger
    FOR EACH ROW EXECUTE FUNCTION asf_guard_internal_budget_ledger_key();

-- Every work-item budget writer participates in the same transaction-scoped
-- lock as admission, including direct ledger consumption/adjustment writers.
CREATE FUNCTION asf_lock_budget_ledger_work_item() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.work_item_id IS NOT NULL THEN
        PERFORM pg_advisory_xact_lock(hashtextextended(
            'admission:' || NEW.tenant_id::text || ':budget:' || NEW.work_item_id::text,
            0
        ));
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER budget_ledger_serializes_with_admission
    BEFORE INSERT ON budget_ledger
    FOR EACH ROW EXECUTE FUNCTION asf_lock_budget_ledger_work_item();

CREATE FUNCTION asf_assert_reservation_set_event() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    required_event_type text;
    required_previous_fence bigint;
    required_idempotency_key text;
BEGIN
    IF NEW.state = 'ACTIVE' THEN
        required_event_type := 'ACQUIRED';
        required_previous_fence := 0;
        required_idempotency_key := NEW.idempotency_key;
    ELSE
        required_event_type := NEW.state;
        required_previous_fence := NEW.fence_token - 1;
        required_idempotency_key := NEW.transition_idempotency_key;
    END IF;
    IF NOT EXISTS (
        SELECT 1
        FROM reservation_set_events AS event
        WHERE event.tenant_id = NEW.tenant_id
          AND event.reservation_set_id = NEW.id
          AND event.event_type = required_event_type
          AND event.previous_fence_token = required_previous_fence
          AND event.fence_token = NEW.fence_token
          AND event.idempotency_key = required_idempotency_key
    ) THEN
        RAISE EXCEPTION 'reservation set % has no matching fenced audit event', NEW.id
            USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER reservation_sets_require_event
    AFTER INSERT OR UPDATE ON reservation_sets
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION asf_assert_reservation_set_event();

CREATE TRIGGER audit_events_append_only
    BEFORE UPDATE OR DELETE ON audit_events
    FOR EACH ROW EXECUTE FUNCTION asf_reject_row_mutation();

-- Session identity and generation are immutable.  Opening a session is fenced
-- by the worker's current generation; closing/revoking it preserves the row as
-- durable provenance for runs and raw events.
CREATE FUNCTION asf_guard_worker_session() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    current_worker_generation bigint;
BEGIN
    IF TG_OP = 'INSERT' THEN
        SELECT worker.generation
        INTO current_worker_generation
        FROM workers AS worker
        WHERE worker.tenant_id = NEW.tenant_id
          AND worker.id = NEW.worker_id
        FOR KEY SHARE;

        IF NOT FOUND OR current_worker_generation <> NEW.worker_generation THEN
            RAISE EXCEPTION 'worker session generation % is stale for worker %',
                NEW.worker_generation, NEW.worker_id
                USING ERRCODE = '40001';
        END IF;
        IF NEW.status = 'ACTIVE' AND NEW.expires_at <= clock_timestamp() THEN
            RAISE EXCEPTION 'active worker session must expire in the future'
                USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.tenant_id <> OLD.tenant_id
       OR NEW.id <> OLD.id
       OR NEW.worker_id <> OLD.worker_id
       OR NEW.worker_generation <> OLD.worker_generation
       OR NEW.started_at <> OLD.started_at THEN
        RAISE EXCEPTION 'worker session identity and generation are immutable'
            USING ERRCODE = '55000';
    END IF;
    IF OLD.status <> 'ACTIVE' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'closed or revoked worker sessions are immutable'
            USING ERRCODE = '55000';
    END IF;
    IF OLD.status = 'ACTIVE' AND NEW.status NOT IN ('ACTIVE', 'CLOSED', 'REVOKED') THEN
        RAISE EXCEPTION 'invalid worker session status transition'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.status = 'ACTIVE' AND NEW.expires_at <= clock_timestamp() THEN
        RAISE EXCEPTION 'active worker session must expire in the future'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER worker_session_guard
    BEFORE INSERT OR UPDATE ON worker_sessions
    FOR EACH ROW EXECUTE FUNCTION asf_guard_worker_session();

CREATE TRIGGER worker_sessions_cannot_be_deleted
    BEFORE DELETE ON worker_sessions
    FOR EACH ROW EXECUTE FUNCTION asf_reject_row_mutation();

CREATE FUNCTION asf_guard_worker_generation() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.generation IS DISTINCT FROM OLD.generation THEN
        IF NEW.generation <= OLD.generation THEN
            RAISE EXCEPTION 'worker generation must increase monotonically'
                USING ERRCODE = '40001';
        END IF;
        IF EXISTS (
            SELECT 1
            FROM worker_sessions AS session
            WHERE session.tenant_id = OLD.tenant_id
              AND session.worker_id = OLD.id
              AND session.status = 'ACTIVE'
        ) THEN
            RAISE EXCEPTION 'close the active worker session before advancing generation'
                USING ERRCODE = '55000';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER worker_generation_guard
    BEFORE UPDATE ON workers
    FOR EACH ROW EXECUTE FUNCTION asf_guard_worker_generation();

CREATE FUNCTION asf_live_worker_session(
    candidate_tenant uuid,
    candidate_session uuid,
    candidate_worker uuid,
    candidate_generation bigint
) RETURNS boolean
LANGUAGE sql
VOLATILE
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM worker_sessions AS session
        JOIN workers AS worker
          ON worker.tenant_id = session.tenant_id
         AND worker.id = session.worker_id
        WHERE session.tenant_id = candidate_tenant
          AND session.id = candidate_session
          AND session.worker_id = candidate_worker
          AND session.worker_generation = candidate_generation
          AND session.status = 'ACTIVE'
          AND session.expires_at > clock_timestamp()
          AND worker.generation = candidate_generation
    );
$$;

CREATE FUNCTION asf_assert_run_worker_session() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT asf_live_worker_session(
        NEW.tenant_id,
        NEW.worker_session_id,
        NEW.worker_id,
        NEW.worker_generation
    ) THEN
        RAISE EXCEPTION 'run is bound to a closed, expired, or stale worker session'
            USING ERRCODE = '40001';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER run_worker_session_guard
    BEFORE INSERT OR UPDATE OF worker_session_id, worker_id, worker_generation ON runs
    FOR EACH ROW EXECUTE FUNCTION asf_assert_run_worker_session();

CREATE FUNCTION asf_assert_raw_event_worker_session() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT asf_live_worker_session(
        NEW.tenant_id,
        NEW.worker_session_id,
        NEW.worker_id,
        NEW.worker_generation
    ) THEN
        RAISE EXCEPTION 'raw run event is bound to a closed, expired, or stale worker session'
            USING ERRCODE = '40001';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER raw_event_worker_session_guard
    BEFORE INSERT ON raw_run_events
    FOR EACH ROW EXECUTE FUNCTION asf_assert_raw_event_worker_session();

CREATE FUNCTION asf_assert_dead_job_escalation() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.status = 'DEAD' THEN
        IF NEW.work_item_id IS NOT NULL AND NOT EXISTS (
            SELECT 1
            FROM escalations AS escalation
            WHERE escalation.tenant_id = NEW.tenant_id
              AND escalation.work_item_id = NEW.work_item_id
              AND escalation.id = NEW.dead_letter_escalation_id
              AND escalation.category = 'WORKFLOW_JOB_EXHAUSTED'
              AND escalation.status IN ('OPEN', 'ACKNOWLEDGED')
              AND btrim(escalation.owner_id) <> ''
              AND btrim(escalation.required_action) <> ''
              AND escalation.deadline > NEW.dead_lettered_at
              AND jsonb_typeof(escalation.retry_policy) = 'object'
        ) THEN
            RAISE EXCEPTION 'dead workflow job % has no open owned exhaustion escalation', NEW.id
                USING ERRCODE = '23514';
        ELSIF NEW.work_item_id IS NULL AND NOT EXISTS (
            SELECT 1
            FROM operational_incidents AS incident
            WHERE incident.tenant_id = NEW.tenant_id
              AND incident.workflow_job_id = NEW.id
              AND incident.id = NEW.dead_letter_operational_incident_id
              AND incident.category = 'WORKFLOW_JOB_EXHAUSTED'
              AND incident.status IN ('OPEN', 'ACKNOWLEDGED')
              AND btrim(incident.owner_id) <> ''
              AND btrim(incident.required_action) <> ''
              AND jsonb_typeof(incident.evidence_references) = 'array'
              AND jsonb_array_length(incident.evidence_references) > 0
              AND incident.deadline > NEW.dead_lettered_at
              AND jsonb_typeof(incident.retry_policy) = 'object'
        ) THEN
            RAISE EXCEPTION 'dead operational workflow job % has no open owned incident', NEW.id
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER workflow_jobs_require_dead_letter_escalation
    AFTER INSERT OR UPDATE ON workflow_jobs
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION asf_assert_dead_job_escalation();

-- The database mirrors the aggregate transition graph so a stale or ad-hoc
-- writer cannot move acknowledged work backwards or defeat optimistic fencing.
CREATE FUNCTION asf_guard_work_item_update() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    transition_allowed boolean;
BEGIN
    IF OLD.accepted_at IS NOT NULL
       AND NEW.accepted_at IS DISTINCT FROM OLD.accepted_at THEN
        RAISE EXCEPTION 'work item acceptance is durable and cannot be changed or cleared'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.aggregate_version <> OLD.aggregate_version + 1 THEN
        RAISE EXCEPTION 'work item aggregate_version must advance by exactly one (expected %, got %)',
            OLD.aggregate_version + 1,
            NEW.aggregate_version
            USING ERRCODE = '40001';
    END IF;

    IF NEW.state = OLD.state THEN
        RETURN NEW;
    END IF;

    transition_allowed := CASE OLD.state
        WHEN 'DISCOVERED' THEN NEW.state = 'READINESS_PENDING'
        WHEN 'READINESS_PENDING' THEN NEW.state IN (
            'NEEDS_SPEC', 'READY', 'REFUSED', 'WAITING_DEPENDENCY'
        )
        WHEN 'NEEDS_SPEC' THEN NEW.state IN ('READINESS_PENDING', 'REFUSED')
        WHEN 'READY' THEN NEW.state IN ('ACCEPTED', 'READINESS_PENDING', 'REFUSED')
        WHEN 'ACCEPTED' THEN NEW.state IN (
            'PLANNED', 'SCHEDULED', 'WAITING_APPROVAL', 'WAITING_DEPENDENCY',
            'CANCEL_REQUESTED', 'ESCALATED'
        )
        WHEN 'PLANNED' THEN NEW.state IN (
            'SCHEDULED', 'WAITING_APPROVAL', 'WAITING_DEPENDENCY',
            'CANCEL_REQUESTED', 'ESCALATED'
        )
        WHEN 'SCHEDULED' THEN NEW.state IN (
            'DISPATCHING', 'WAITING_APPROVAL', 'WAITING_DEPENDENCY',
            'RETRY_SCHEDULED', 'CANCEL_REQUESTED', 'ESCALATED'
        )
        WHEN 'DISPATCHING' THEN NEW.state IN (
            'RUNNING', 'RETRY_SCHEDULED', 'BLOCKED_EXTERNAL',
            'CANCEL_REQUESTED', 'ESCALATED', 'QUARANTINED'
        )
        WHEN 'RUNNING' THEN NEW.state IN (
            'VERIFYING_OUTCOME', 'WAITING_APPROVAL', 'RETRY_SCHEDULED',
            'BLOCKED_EXTERNAL', 'BUDGET_EXHAUSTED', 'CANCEL_REQUESTED',
            'ESCALATED', 'QUARANTINED'
        )
        WHEN 'VERIFYING_OUTCOME' THEN NEW.state IN (
            'TARGET_REACHED', 'RETRY_SCHEDULED', 'BLOCKED_EXTERNAL',
            'WAITING_APPROVAL', 'ESCALATED', 'QUARANTINED'
        )
        WHEN 'TARGET_REACHED' THEN NEW.state IN ('CLOSING_SOURCE', 'QUARANTINED')
        WHEN 'CLOSING_SOURCE' THEN NEW.state IN ('CLOSED', 'BLOCKED_EXTERNAL', 'ESCALATED')
        WHEN 'WAITING_DEPENDENCY' THEN NEW.state IN (
            'SCHEDULED', 'READINESS_PENDING', 'CANCEL_REQUESTED', 'ESCALATED'
        )
        WHEN 'WAITING_APPROVAL' THEN NEW.state IN (
            'SCHEDULED', 'DISPATCHING', 'RUNNING', 'VERIFYING_OUTCOME',
            'CANCEL_REQUESTED', 'ESCALATED', 'REFUSED'
        )
        WHEN 'RETRY_SCHEDULED' THEN NEW.state IN (
            'SCHEDULED', 'READINESS_PENDING', 'CANCEL_REQUESTED', 'ESCALATED'
        )
        WHEN 'BLOCKED_EXTERNAL' THEN NEW.state IN (
            'RETRY_SCHEDULED', 'RUNNING', 'CLOSING_SOURCE', 'CANCEL_REQUESTED',
            'ESCALATED', 'QUARANTINED'
        )
        WHEN 'BUDGET_EXHAUSTED' THEN NEW.state IN (
            'WAITING_APPROVAL', 'RETRY_SCHEDULED', 'CANCEL_REQUESTED', 'ESCALATED'
        )
        WHEN 'QUARANTINED' THEN NEW.state IN (
            'RETRY_SCHEDULED', 'CANCEL_REQUESTED', 'ESCALATED'
        )
        WHEN 'CANCEL_REQUESTED' THEN NEW.state IN (
            'CANCELLED', 'BLOCKED_EXTERNAL', 'ESCALATED'
        )
        WHEN 'ESCALATED' THEN NEW.state IN (
            'READINESS_PENDING', 'SCHEDULED', 'RETRY_SCHEDULED',
            'CANCEL_REQUESTED', 'CANCELLED'
        )
        ELSE false
    END;

    IF NOT transition_allowed THEN
        RAISE EXCEPTION 'invalid work item transition from % to %', OLD.state, NEW.state
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER work_item_transition_guard
    BEFORE UPDATE ON work_items
    FOR EACH ROW EXECUTE FUNCTION asf_guard_work_item_update();

CREATE FUNCTION asf_reject_work_item_delete() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'work items are durable ledger records; transition to a terminal state instead'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER work_items_cannot_be_deleted
    BEFORE DELETE ON work_items
    FOR EACH ROW EXECUTE FUNCTION asf_reject_work_item_delete();

CREATE FUNCTION asf_accountability_reference_is_live(
    candidate_tenant uuid,
    candidate_work_item uuid,
    candidate_type text,
    candidate_reference uuid,
    candidate_wake_or_deadline timestamptz,
    candidate_authority_or_effect_active boolean
) RETURNS boolean
LANGUAGE sql
VOLATILE
AS $$
    SELECT CASE candidate_type
        WHEN 'WORKFLOW' THEN EXISTS (
            SELECT 1
            FROM workflow_instances AS workflow
            WHERE workflow.tenant_id = candidate_tenant
              AND workflow.work_item_id = candidate_work_item
              AND workflow.id = candidate_reference
              AND workflow.state IN ('ACTIVE', 'WAITING')
              AND candidate_wake_or_deadline IS NULL
              AND (
                  EXISTS (
                      SELECT 1
                      FROM workflow_jobs AS job
                      WHERE job.tenant_id = workflow.tenant_id
                        AND job.work_item_id = workflow.work_item_id
                        AND job.workflow_instance_id = workflow.id
                        AND (
                            (
                                job.status IN ('PENDING', 'RETRY')
                                AND job.attempt_count < job.max_attempts
                            )
                            OR (
                                job.status = 'RUNNING'
                                AND job.lease_expires_at > clock_timestamp()
                            )
                        )
                  )
                  OR EXISTS (
                      SELECT 1
                      FROM workflow_timers AS timer
                      WHERE timer.tenant_id = workflow.tenant_id
                        AND timer.work_item_id = workflow.work_item_id
                        AND timer.workflow_instance_id = workflow.id
                        AND timer.status = 'SCHEDULED'
                  )
              )
        )
        WHEN 'RUN' THEN EXISTS (
            SELECT 1
            FROM runs AS run
            WHERE run.tenant_id = candidate_tenant
              AND run.work_item_id = candidate_work_item
              AND run.id = candidate_reference
              AND run.authoritative
              AND run.state IN (
                  'ADOPTED',
                  'RUNNING',
                  'WAITING_APPROVAL',
                  'VERIFYING',
                  'CANCEL_REQUESTED'
              )
              AND candidate_wake_or_deadline IS NULL
        )
        WHEN 'TIMER' THEN EXISTS (
            SELECT 1
            FROM workflow_timers AS timer
            WHERE timer.tenant_id = candidate_tenant
              AND timer.work_item_id = candidate_work_item
              AND timer.id = candidate_reference
              AND timer.status = 'SCHEDULED'
              AND timer.due_at = candidate_wake_or_deadline
        )
        WHEN 'RETRY' THEN EXISTS (
            SELECT 1
            FROM workflow_timers AS timer
            WHERE timer.tenant_id = candidate_tenant
              AND timer.work_item_id = candidate_work_item
              AND timer.id = candidate_reference
              AND timer.status = 'SCHEDULED'
              AND timer.timer_type = 'RETRY'
              AND timer.due_at = candidate_wake_or_deadline
        )
        WHEN 'APPROVAL' THEN EXISTS (
            SELECT 1
            FROM approvals AS approval
            WHERE approval.tenant_id = candidate_tenant
              AND approval.work_item_id = candidate_work_item
              AND approval.id = candidate_reference
              AND approval.status = 'PENDING'
              AND approval.expires_at > clock_timestamp()
              AND approval.expires_at = candidate_wake_or_deadline
        )
        WHEN 'ESCALATION' THEN EXISTS (
            SELECT 1
            FROM escalations AS escalation
            WHERE escalation.tenant_id = candidate_tenant
              AND escalation.work_item_id = candidate_work_item
              AND escalation.id = candidate_reference
              AND escalation.status IN ('OPEN', 'ACKNOWLEDGED')
              AND escalation.deadline = candidate_wake_or_deadline
              AND escalation.authority_or_effect_active =
                  candidate_authority_or_effect_active
        )
        WHEN 'CLOSURE' THEN EXISTS (
            SELECT 1
            FROM evidence_bundles AS evidence
            JOIN work_items AS work
              ON work.tenant_id = evidence.tenant_id
             AND work.id = evidence.work_item_id
            JOIN attempts AS attempt
              ON attempt.tenant_id = work.tenant_id
             AND attempt.id = work.current_attempt_id
             AND attempt.work_item_id = work.id
            JOIN runs AS run
              ON run.tenant_id = evidence.tenant_id
             AND run.id = evidence.run_id
             AND run.work_item_id = evidence.work_item_id
             AND run.attempt_id = evidence.attempt_id
             AND run.worker_id = evidence.worker_id
            JOIN work_orders AS work_order
              ON work_order.tenant_id = run.tenant_id
             AND work_order.id = run.work_order_id
             AND work_order.work_item_id = run.work_item_id
             AND work_order.attempt_id = run.attempt_id
            WHERE evidence.tenant_id = candidate_tenant
              AND evidence.work_item_id = candidate_work_item
              AND evidence.id = candidate_reference
              AND evidence.attempt_id = attempt.id
              AND evidence.base_sha = attempt.base_sha
              AND evidence.work_order_digest = attempt.work_order_digest
              AND evidence.work_order_digest = work_order.payload_digest
              AND evidence.requested_target = work.closure_target
              AND evidence.worker_generation = run.worker_generation
              AND run.authoritative
              AND run.state = 'SUCCEEDED'
              AND evidence.target_satisfied
              AND candidate_wake_or_deadline IS NULL
              AND EXISTS (
                  SELECT 1
                  FROM evidence_verifications AS verification
                  WHERE verification.tenant_id = evidence.tenant_id
                    AND verification.evidence_id = evidence.id
                    AND verification.expectation_digest =
                        run.evidence_expectation_digest
                    AND verification.status = 'VALID'
              )
        )
        WHEN 'CANCELLATION' THEN EXISTS (
            SELECT 1
            FROM audit_events AS audit
            WHERE audit.tenant_id = candidate_tenant
              AND audit.work_item_id = candidate_work_item
              AND audit.id = candidate_reference
              AND audit.action IN ('WORK_ITEM_CANCELLED', 'work_item.cancelled')
              AND candidate_wake_or_deadline IS NULL
        )
        ELSE false
    END;
$$;

CREATE FUNCTION asf_assert_accountability_reference() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    current_anchor accountability_anchors%ROWTYPE;
BEGIN
    SELECT *
    INTO current_anchor
    FROM accountability_anchors AS anchor
    WHERE anchor.tenant_id = NEW.tenant_id
      AND anchor.work_item_id = NEW.work_item_id;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    IF NOT asf_accountability_reference_is_live(
        current_anchor.tenant_id,
        current_anchor.work_item_id,
        current_anchor.anchor_type,
        current_anchor.reference_id,
        current_anchor.wake_or_deadline_at,
        current_anchor.authority_or_effect_active
    ) THEN
        RAISE EXCEPTION 'accountability anchor % does not reference live % progress for work item %',
            current_anchor.reference_id,
            current_anchor.anchor_type,
            current_anchor.work_item_id
            USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER accountability_anchor_reference_guard
    AFTER INSERT OR UPDATE ON accountability_anchors
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION asf_assert_accountability_reference();

CREATE FUNCTION asf_assert_referencing_accountability_anchors() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    candidate_tenant uuid;
    candidate_reference uuid;
BEGIN
    candidate_tenant := OLD.tenant_id;
    candidate_reference := OLD.id;

    IF EXISTS (
        SELECT 1
        FROM accountability_anchors AS anchor
        WHERE anchor.tenant_id = candidate_tenant
          AND anchor.reference_id = candidate_reference
          AND NOT asf_accountability_reference_is_live(
              anchor.tenant_id,
              anchor.work_item_id,
              anchor.anchor_type,
              anchor.reference_id,
              anchor.wake_or_deadline_at,
              anchor.authority_or_effect_active
          )
    ) THEN
        RAISE EXCEPTION 'mutation would leave an accountability anchor without live progress: %',
            candidate_reference
            USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER workflow_instance_anchor_guard
    AFTER UPDATE OR DELETE ON workflow_instances
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION asf_assert_referencing_accountability_anchors();

-- A WORKFLOW anchor is live only while its instance has a claimable/running
-- job or scheduled timer. Re-evaluate that parent anchor when either child
-- changes so completing or dead-lettering the last child must atomically
-- install the next job, timer, run, approval, escalation, or terminal anchor.
CREATE FUNCTION asf_assert_workflow_anchor_for_child() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    candidate_tenant uuid;
    old_workflow_id uuid;
    new_workflow_id uuid;
BEGIN
    candidate_tenant := OLD.tenant_id;
    old_workflow_id := OLD.workflow_instance_id;
    IF TG_OP <> 'DELETE' THEN
        new_workflow_id := NEW.workflow_instance_id;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM accountability_anchors AS anchor
        WHERE anchor.tenant_id = candidate_tenant
          AND anchor.anchor_type = 'WORKFLOW'
          AND anchor.reference_id IN (old_workflow_id, new_workflow_id)
          AND NOT asf_accountability_reference_is_live(
              anchor.tenant_id,
              anchor.work_item_id,
              anchor.anchor_type,
              anchor.reference_id,
              anchor.wake_or_deadline_at,
              anchor.authority_or_effect_active
          )
    ) THEN
        RAISE EXCEPTION 'workflow child mutation would strand an accountability anchor'
            USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER workflow_job_parent_anchor_guard
    AFTER UPDATE OR DELETE ON workflow_jobs
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION asf_assert_workflow_anchor_for_child();

CREATE CONSTRAINT TRIGGER workflow_timer_parent_anchor_guard
    AFTER UPDATE OR DELETE ON workflow_timers
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION asf_assert_workflow_anchor_for_child();

CREATE CONSTRAINT TRIGGER run_anchor_guard
    AFTER UPDATE OR DELETE ON runs
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION asf_assert_referencing_accountability_anchors();

CREATE CONSTRAINT TRIGGER workflow_timer_anchor_guard
    AFTER UPDATE OR DELETE ON workflow_timers
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION asf_assert_referencing_accountability_anchors();

CREATE CONSTRAINT TRIGGER approval_anchor_guard
    AFTER UPDATE OR DELETE ON approvals
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION asf_assert_referencing_accountability_anchors();

CREATE CONSTRAINT TRIGGER escalation_anchor_guard
    AFTER UPDATE OR DELETE ON escalations
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION asf_assert_referencing_accountability_anchors();

-- Accountability is enforced at transaction commit so acceptance and anchor
-- creation can occur atomically in either statement order.
CREATE FUNCTION asf_assert_accountability_anchor() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    candidate_tenant uuid;
    candidate_work_item uuid;
    current_state text;
    current_accepted_at timestamptz;
    current_anchor_type text;
    current_reference_id uuid;
    current_wake_or_deadline timestamptz;
    current_authority_or_effect_active boolean;
BEGIN
    IF TG_TABLE_NAME = 'work_items' THEN
        candidate_tenant := NEW.tenant_id;
        candidate_work_item := NEW.id;
    ELSE
        candidate_tenant := OLD.tenant_id;
        candidate_work_item := OLD.work_item_id;
    END IF;

    SELECT
        work.state,
        work.accepted_at,
        anchor.anchor_type,
        anchor.reference_id,
        anchor.wake_or_deadline_at,
        anchor.authority_or_effect_active
    INTO
        current_state,
        current_accepted_at,
        current_anchor_type,
        current_reference_id,
        current_wake_or_deadline,
        current_authority_or_effect_active
    FROM work_items AS work
    LEFT JOIN accountability_anchors AS anchor
      ON anchor.tenant_id = work.tenant_id
     AND anchor.work_item_id = work.id
    WHERE work.tenant_id = candidate_tenant
      AND work.id = candidate_work_item;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    IF current_accepted_at IS NOT NULL AND current_anchor_type IS NULL THEN
        RAISE EXCEPTION 'accepted work item % has no accountability anchor', candidate_work_item
            USING ERRCODE = '23514';
    END IF;

    IF current_anchor_type IS NOT NULL
       AND NOT asf_accountability_reference_is_live(
           candidate_tenant,
           candidate_work_item,
           current_anchor_type,
           current_reference_id,
           current_wake_or_deadline,
           current_authority_or_effect_active
       ) THEN
        RAISE EXCEPTION 'work item % has a non-live % accountability anchor',
            candidate_work_item,
            current_anchor_type
            USING ERRCODE = '23514';
    END IF;

    IF (current_state = 'CLOSED' AND current_anchor_type <> 'CLOSURE')
       OR (current_state = 'CANCELLED' AND current_anchor_type <> 'CANCELLATION')
       OR (current_state = 'WAITING_APPROVAL' AND current_anchor_type <> 'APPROVAL')
       OR (current_state = 'RETRY_SCHEDULED' AND current_anchor_type <> 'RETRY')
       OR (current_state = 'ESCALATED' AND current_anchor_type <> 'ESCALATION') THEN
        RAISE EXCEPTION 'work item state % is incompatible with accountability anchor %',
            current_state,
            current_anchor_type
            USING ERRCODE = '23514';
    END IF;

    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER work_items_require_accountability
    AFTER INSERT OR UPDATE ON work_items
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION asf_assert_accountability_anchor();

CREATE CONSTRAINT TRIGGER accountability_anchor_removal_guard
    AFTER UPDATE OR DELETE ON accountability_anchors
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION asf_assert_accountability_anchor();
